print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("Ola mundo")
print("ola novamente mundo")
